-- 005: Descriptions on every table and column (from the data dictionary), so psql shows what each is for.
-- Metadata only: no data or structure changes. Run as the database owner (postgres):
--   psql -U postgres -d heyhr -v ON_ERROR_STOP=1 -f database/migrations/005_comments.sql

BEGIN;

COMMENT ON TABLE company_settings IS 'Single row of company-wide settings: identity, sign-in security and tardiness flags.';
COMMENT ON COLUMN company_settings.id IS 'Always 1; the table holds one row.';
COMMENT ON COLUMN company_settings.company_name IS 'Legal or trade name shown on payslips and certificates.';
COMMENT ON COLUMN company_settings.tin IS 'Company TIN, 000-000-000-00000.';
COMMENT ON COLUMN company_settings.address IS 'Registered business address.';
COMMENT ON COLUMN company_settings.contact_email IS 'HR contact address shown to employees.';
COMMENT ON COLUMN company_settings.min_password_length IS 'Minimum password length for user accounts.';
COMMENT ON COLUMN company_settings.lock_after_failed IS 'Failed sign-ins before an account locks.';
COMMENT ON COLUMN company_settings.lock_minutes IS 'How long a locked account stays locked.';
COMMENT ON COLUMN company_settings.idle_minutes IS 'Idle time before a session signs out.';
COMMENT ON COLUMN company_settings.tardy_consecutive_days IS 'Flag someone late this many work days in a row (0 = off).';
COMMENT ON COLUMN company_settings.tardy_per_month IS 'Flag someone late this many times in a month (0 = off).';
COMMENT ON COLUMN company_settings.updated_at IS 'Last change.';
COMMENT ON COLUMN company_settings.updated_by IS 'Account that made the last change.';
COMMENT ON TABLE org_units IS 'The organization tree: one company, its branches, their departments and teams (clusters).';
COMMENT ON COLUMN org_units.id IS 'Primary key.';
COMMENT ON COLUMN org_units.unit_type IS 'Level in the tree.';
COMMENT ON COLUMN org_units.name IS 'Display name, e.g. Cebu HQ, Tax Advisory, RPM.';
COMMENT ON COLUMN org_units.code IS 'Short code used in tables and IDs, e.g. CEB, TAX.';
COMMENT ON COLUMN org_units.parent_id IS 'Parent unit; null only for the company.';
COMMENT ON COLUMN org_units.head_employee_id IS 'Head of the unit (department head, partner).';
COMMENT ON COLUMN org_units.address IS 'Street address; branches only.';
COMMENT ON COLUMN org_units.is_active IS 'Inactive units stay for history but can''t take new people.';
COMMENT ON TABLE positions IS 'Budgeted job positions within a department.';
COMMENT ON COLUMN positions.id IS 'Primary key.';
COMMENT ON COLUMN positions.title IS 'Job title, e.g. Experienced Associate.';
COMMENT ON COLUMN positions.code IS 'Short code, e.g. EA.';
COMMENT ON COLUMN positions.department_id IS 'Department the position belongs to.';
COMMENT ON COLUMN positions.job_level IS 'Seniority band.';
COMMENT ON COLUMN positions.default_employment_type IS 'Type new hires into this position usually start on.';
COMMENT ON COLUMN positions.budgeted_slots IS 'Approved headcount for the position.';
COMMENT ON COLUMN positions.reports_to_position_id IS 'Position this one reports to.';
COMMENT ON COLUMN positions.description IS 'Duties summary.';
COMMENT ON COLUMN positions.is_active IS 'Inactive positions can''t take new hires.';
COMMENT ON TABLE holidays IS 'Philippine regular and special non-working days, by proclamation.';
COMMENT ON COLUMN holidays.holiday_date IS 'The day.';
COMMENT ON COLUMN holidays.name IS 'e.g. Araw ng Kagitingan.';
COMMENT ON COLUMN holidays.holiday_type IS 'Regular holidays pay 200%; special days 130%.';
COMMENT ON COLUMN holidays.source IS 'Proclamation number or reference.';
COMMENT ON TABLE employees IS 'The employee master record (201 File core). Fields marked BRD follow the New Employees Template (BRD v1.1, 11.2.1). Government numbers and BASIC_RATE are HR- and Payroll-only.';
COMMENT ON COLUMN employees.employee_id IS 'BRD. Unique employee identifier. Auto-generated if blank (MSMA-00001).';
COMMENT ON COLUMN employees.last_name IS 'BRD. Surname. Letters only (spaces, hyphens, apostrophes, periods allowed).';
COMMENT ON COLUMN employees.first_name IS 'BRD. Given name. Letters only.';
COMMENT ON COLUMN employees.middle_name IS 'BRD. Middle name. Letters only.';
COMMENT ON COLUMN employees.suffix IS 'Jr., Sr., III.';
COMMENT ON COLUMN employees.birth_date IS 'BRD. Date of birth. Age must be 18 or older (checked by trigger).';
COMMENT ON COLUMN employees.sex IS 'BRD. Gender. From the allowed values only.';
COMMENT ON COLUMN employees.civil_status IS 'BRD. Marital status. From the allowed values only.';
COMMENT ON COLUMN employees.mobile_no IS 'BRD. Mobile number, 11 digits: 09XXXXXXXXX. Unique.';
COMMENT ON COLUMN employees.email IS 'BRD. Email address (work). Valid email format. Unique.';
COMMENT ON COLUMN employees.date_hired IS 'BRD. First day of employment. Not more than 30 days in the future (checked by trigger).';
COMMENT ON COLUMN employees.employment_status IS 'BRD. Employment type.';
COMMENT ON COLUMN employees.tin IS 'BRD. Tax Identification Number. Required before first payroll. Unique.';
COMMENT ON COLUMN employees.sss_no IS 'BRD. SSS number. Required before first payroll. Unique.';
COMMENT ON COLUMN employees.philhealth_no IS 'BRD. PhilHealth number. Required before first payroll. Unique.';
COMMENT ON COLUMN employees.pagibig_no IS 'BRD. Pag-IBIG MID number. Required before first payroll. Unique.';
COMMENT ON COLUMN employees.basic_rate IS 'BRD. Basic monthly salary in PHP; must be > 0. Restricted to HR and Payroll.';
COMMENT ON COLUMN employees.nationality IS 'Nationality.';
COMMENT ON COLUMN employees.photo_file_id IS 'ID photo.';
COMMENT ON COLUMN employees.personal_email IS 'Personal email.';
COMMENT ON COLUMN employees.address_line IS 'House no., street, barangay.';
COMMENT ON COLUMN employees.city IS 'City or municipality.';
COMMENT ON COLUMN employees.province IS 'Province.';
COMMENT ON COLUMN employees.emergency_name IS 'Emergency contact person.';
COMMENT ON COLUMN employees.emergency_relationship IS 'Their relationship to the employee.';
COMMENT ON COLUMN employees.emergency_phone IS 'Their phone number.';
COMMENT ON COLUMN employees.position_id IS 'Current position.';
COMMENT ON COLUMN employees.org_unit_id IS 'Team, or the department when not in a team.';
COMMENT ON COLUMN employees.supervisor_id IS 'Immediate supervisor.';
COMMENT ON COLUMN employees.record_status IS 'Whether the person is currently working here.';
COMMENT ON COLUMN employees.regularization_date IS 'When the employee became REGULAR.';
COMMENT ON COLUMN employees.separation_date IS 'Last day, once separated.';
COMMENT ON COLUMN employees.work_schedule IS 'Schedule as shown on the 201 File, e.g. Mon-Fri, 8:30 AM - 5:00 PM.';
COMMENT ON COLUMN employees.default_shift_id IS 'Usual shift; overridden per day in schedule_overrides.';
COMMENT ON COLUMN employees.face_enrolled IS 'Face template enrolled for face-scan clock-in.';
COMMENT ON COLUMN employees.created_at IS 'When the row was created.';
COMMENT ON COLUMN employees.updated_at IS 'Last change.';
COMMENT ON TABLE dependents IS 'Spouse and children, for HMO enrollment and leave eligibility.';
COMMENT ON COLUMN dependents.id IS 'Primary key.';
COMMENT ON COLUMN dependents.employee_id IS 'The employee this belongs to.';
COMMENT ON COLUMN dependents.full_name IS 'Dependent''s name.';
COMMENT ON COLUMN dependents.relationship IS 'Relationship.';
COMMENT ON COLUMN dependents.birth_date IS 'Birth date (children).';
COMMENT ON COLUMN dependents.hmo_enrolled IS 'Enrolled as an HMO dependent.';
COMMENT ON TABLE files IS 'Uploaded files: documents, receipts, photos. Kept in `content` for now; object storage later.';
COMMENT ON COLUMN files.id IS 'Primary key.';
COMMENT ON COLUMN files.storage_key IS 'Object-storage key.';
COMMENT ON COLUMN files.file_name IS 'Original file name.';
COMMENT ON COLUMN files.content_type IS 'MIME type.';
COMMENT ON COLUMN files.size_bytes IS 'File size.';
COMMENT ON COLUMN files.sha256 IS 'Checksum, to catch duplicates.';
COMMENT ON COLUMN files.content IS 'The file itself, while files are kept in the database (null once moved to object storage).';
COMMENT ON COLUMN files.uploaded_by IS 'Account that uploaded it.';
COMMENT ON COLUMN files.uploaded_at IS 'Upload time.';
COMMENT ON TABLE employee_documents IS 'Pre-employment and identity documents in the 201 File checklist.';
COMMENT ON COLUMN employee_documents.id IS 'Primary key.';
COMMENT ON COLUMN employee_documents.employee_id IS 'The employee this belongs to.';
COMMENT ON COLUMN employee_documents.document_type IS 'Checklist item.';
COMMENT ON COLUMN employee_documents.status IS 'Where it stands.';
COMMENT ON COLUMN employee_documents.file_id IS 'The uploaded scan.';
COMMENT ON COLUMN employee_documents.file_name IS 'Name of the submitted file.';
COMMENT ON COLUMN employee_documents.submitted_at IS 'When it was uploaded.';
COMMENT ON COLUMN employee_documents.verified_by IS 'HR account that verified it.';
COMMENT ON COLUMN employee_documents.verified_by_name IS 'Name of who verified it, kept if the account goes.';
COMMENT ON COLUMN employee_documents.verified_at IS 'When it was verified.';
COMMENT ON COLUMN employee_documents.id_type IS 'For government IDs: UMID, Passport, Driver''s License…';
COMMENT ON COLUMN employee_documents.reference_no IS 'ID or license number. Sensitive.';
COMMENT ON COLUMN employee_documents.expires_on IS 'Expiry of the ID, license or clearance; drives renewal alerts.';
COMMENT ON COLUMN employee_documents.note IS 'HR note.';
COMMENT ON TABLE job_events IS 'Employment history: hires, promotions, transfers, salary changes, separations.';
COMMENT ON COLUMN job_events.id IS 'Primary key.';
COMMENT ON COLUMN job_events.employee_id IS 'The employee this belongs to.';
COMMENT ON COLUMN job_events.event_kind IS 'What happened.';
COMMENT ON COLUMN job_events.effective_date IS 'When it takes effect.';
COMMENT ON COLUMN job_events.changes IS 'List of {label, from, to} field changes.';
COMMENT ON COLUMN job_events.remarks IS 'Personnel action notice number or remarks.';
COMMENT ON COLUMN job_events.recorded_by IS 'Account that recorded it.';
COMMENT ON COLUMN job_events.recorded_by_name IS 'Name of who recorded it, kept if the account goes.';
COMMENT ON COLUMN job_events.recorded_at IS 'When it was recorded.';
COMMENT ON TABLE professional_licenses IS 'PRC licenses (CPA, lawyer) and CPD unit progress.';
COMMENT ON COLUMN professional_licenses.id IS 'Primary key.';
COMMENT ON COLUMN professional_licenses.employee_id IS 'The employee this belongs to.';
COMMENT ON COLUMN professional_licenses.license_type IS 'e.g. CPA.';
COMMENT ON COLUMN professional_licenses.license_number IS 'PRC license number.';
COMMENT ON COLUMN professional_licenses.expires_on IS 'License validity.';
COMMENT ON COLUMN professional_licenses.cpd_units_earned IS 'CPD units earned this cycle.';
COMMENT ON COLUMN professional_licenses.cpd_units_required IS 'CPD units required for renewal.';
COMMENT ON COLUMN professional_licenses.cycle_end_date IS 'End of the current CPD compliance cycle.';
COMMENT ON TABLE employee_benefits IS 'HMO and government benefit memberships.';
COMMENT ON COLUMN employee_benefits.id IS 'Primary key.';
COMMENT ON COLUMN employee_benefits.employee_id IS 'The employee this belongs to.';
COMMENT ON COLUMN employee_benefits.benefit_name IS 'e.g. HMO, HMO — Dependent.';
COMMENT ON COLUMN employee_benefits.provider IS 'e.g. Maxicare.';
COMMENT ON COLUMN employee_benefits.member_no IS 'Membership or card number.';
COMMENT ON COLUMN employee_benefits.status IS 'Enrollment status.';
COMMENT ON TABLE performance_reviews IS 'Appraisals, annual and mid-year.';
COMMENT ON COLUMN performance_reviews.id IS 'Primary key.';
COMMENT ON COLUMN performance_reviews.employee_id IS 'The employee this belongs to.';
COMMENT ON COLUMN performance_reviews.review_period IS 'e.g. 2026 Mid-year review.';
COMMENT ON COLUMN performance_reviews.reviewer_id IS 'Who reviewed.';
COMMENT ON COLUMN performance_reviews.rating IS 'Score out of 5.';
COMMENT ON COLUMN performance_reviews.status IS 'Review status.';
COMMENT ON COLUMN performance_reviews.completed_at IS 'When it was completed.';
COMMENT ON TABLE training_records IS 'Assigned trainings and their progress.';
COMMENT ON COLUMN training_records.id IS 'Primary key.';
COMMENT ON COLUMN training_records.employee_id IS 'The employee this belongs to.';
COMMENT ON COLUMN training_records.course IS 'Course name.';
COMMENT ON COLUMN training_records.due_date IS 'Deadline.';
COMMENT ON COLUMN training_records.status IS 'Progress.';
COMMENT ON COLUMN training_records.completed_on IS 'Completion date.';
COMMENT ON TABLE employee_cases IS 'Employee relations cases a partner or HR files.';
COMMENT ON COLUMN employee_cases.id IS 'Primary key.';
COMMENT ON COLUMN employee_cases.employee_id IS 'The employee this belongs to.';
COMMENT ON COLUMN employee_cases.case_type IS 'Kind of case.';
COMMENT ON COLUMN employee_cases.status IS 'Case status.';
COMMENT ON COLUMN employee_cases.summary IS 'What happened and what was done.';
COMMENT ON COLUMN employee_cases.filed_by IS 'Account that filed it.';
COMMENT ON COLUMN employee_cases.filed_on IS 'Filing date.';
COMMENT ON TABLE company_assets IS 'Laptops, IDs, access cards and phones issued to employees.';
COMMENT ON COLUMN company_assets.id IS 'Primary key.';
COMMENT ON COLUMN company_assets.asset_tag IS 'Inventory tag, e.g. LT-0231.';
COMMENT ON COLUMN company_assets.asset_type IS 'e.g. Laptop, Company ID, Access Card.';
COMMENT ON COLUMN company_assets.assigned_employee_id IS 'Who has it now.';
COMMENT ON COLUMN company_assets.issued_on IS 'Issue date.';
COMMENT ON COLUMN company_assets.returned_on IS 'Return date.';
COMMENT ON COLUMN company_assets.status IS 'Condition.';
COMMENT ON TABLE offboarding_cases IS 'Resignations and separations with clearance progress.';
COMMENT ON COLUMN offboarding_cases.id IS 'Primary key.';
COMMENT ON COLUMN offboarding_cases.employee_id IS 'The employee this belongs to.';
COMMENT ON COLUMN offboarding_cases.separation_type IS 'e.g. Voluntary resignation.';
COMMENT ON COLUMN offboarding_cases.reason IS 'Stated reason.';
COMMENT ON COLUMN offboarding_cases.notice_filed_on IS 'When notice was given (30-day rule).';
COMMENT ON COLUMN offboarding_cases.last_day IS 'Last working day.';
COMMENT ON COLUMN offboarding_cases.stage IS 'Where it stands.';
COMMENT ON COLUMN offboarding_cases.clearance IS 'List of {department, status} clearance sign-offs.';
COMMENT ON TABLE certificate_requests IS 'COE and other certificates employees request.';
COMMENT ON COLUMN certificate_requests.id IS 'Primary key.';
COMMENT ON COLUMN certificate_requests.employee_id IS 'The employee this belongs to.';
COMMENT ON COLUMN certificate_requests.certificate_type IS 'e.g. Certificate of Employment.';
COMMENT ON COLUMN certificate_requests.purpose IS 'e.g. Bank loan application.';
COMMENT ON COLUMN certificate_requests.status IS 'Status.';
COMMENT ON COLUMN certificate_requests.requested_at IS 'Request time.';
COMMENT ON COLUMN certificate_requests.released_at IS 'Release time.';
COMMENT ON TABLE shift_templates IS 'Work shifts: Busy season, Peak season, Mid shift, Flexible time.';
COMMENT ON COLUMN shift_templates.id IS 'Short key, e.g. sh-day; new shifts get sh-…';
COMMENT ON COLUMN shift_templates.name IS 'Shift name.';
COMMENT ON COLUMN shift_templates.start_time IS 'Start, local time.';
COMMENT ON COLUMN shift_templates.end_time IS 'End; earlier than start means it ends next day.';
COMMENT ON COLUMN shift_templates.break_minutes IS 'Unpaid break length.';
COMMENT ON COLUMN shift_templates.break_start IS 'When lunch starts; lunch out/in are recorded from it.';
COMMENT ON COLUMN shift_templates.grace_minutes IS 'Minutes after start before someone is late.';
COMMENT ON COLUMN shift_templates.rest_days IS 'Days off, 0 = Sunday.';
COMMENT ON COLUMN shift_templates.is_flexible IS 'Clock in any time in the window; only hours worked count.';
COMMENT ON COLUMN shift_templates.required_hours IS 'Hours a flexible day needs.';
COMMENT ON COLUMN shift_templates.is_active IS 'Retired shifts stay for history.';
COMMENT ON TABLE schedule_overrides IS 'A different shift, or a rest day, for one person on one date.';
COMMENT ON COLUMN schedule_overrides.employee_id IS 'The employee.';
COMMENT ON COLUMN schedule_overrides.work_date IS 'The date.';
COMMENT ON COLUMN schedule_overrides.shift_id IS 'Shift that day; null means a rest day.';
COMMENT ON COLUMN schedule_overrides.set_by IS 'Account that set it.';
COMMENT ON TABLE attendance_devices IS 'Registered biometric scanners and face kiosks.';
COMMENT ON COLUMN attendance_devices.id IS 'Primary key.';
COMMENT ON COLUMN attendance_devices.name IS 'e.g. Cebu HQ lobby, 8F.';
COMMENT ON COLUMN attendance_devices.device_type IS 'Kind of device.';
COMMENT ON COLUMN attendance_devices.branch_id IS 'Branch it''s installed in.';
COMMENT ON COLUMN attendance_devices.serial_no IS 'Hardware serial.';
COMMENT ON COLUMN attendance_devices.is_registered IS 'Punches from unregistered devices get flagged.';
COMMENT ON TABLE punches IS 'Every time-in and time-out. Never deleted; HR sets bad ones aside.';
COMMENT ON COLUMN punches.id IS 'Primary key.';
COMMENT ON COLUMN punches.employee_id IS 'The employee this belongs to.';
COMMENT ON COLUMN punches.work_date IS 'Schedule day it belongs to (an overnight shift''s 6 AM out counts for the day before).';
COMMENT ON COLUMN punches.punched_at IS 'The moment of the punch.';
COMMENT ON COLUMN punches.direction IS 'Time-in or time-out.';
COMMENT ON COLUMN punches.source IS 'Where it came from.';
COMMENT ON COLUMN punches.device_id IS 'Device that recorded it.';
COMMENT ON COLUMN punches.device_label IS 'Where it came from as shown on the record, e.g. Added by HR, Remote · face scan.';
COMMENT ON COLUMN punches.device_branch IS 'Branch of the device (or of the person, for manual punches).';
COMMENT ON COLUMN punches.face_match IS 'Face recognition match, 0–100.';
COMMENT ON COLUMN punches.reason IS 'Why HR added it (manual punches), or the remote work day''s reason.';
COMMENT ON COLUMN punches.recorded_by IS 'Account that added a manual or remote punch.';
COMMENT ON COLUMN punches.recorded_by_name IS 'Name of who recorded it.';
COMMENT ON COLUMN punches.voided_reason IS 'Why HR set it aside.';
COMMENT ON COLUMN punches.voided_by IS 'Who set it aside.';
COMMENT ON COLUMN punches.voided_by_name IS 'Name of who set it aside.';
COMMENT ON COLUMN punches.voided_at IS 'When.';
COMMENT ON COLUMN punches.confirmed_by IS 'HR looked at a flagged punch and kept it.';
COMMENT ON COLUMN punches.confirmed_by_name IS 'Name of who kept it.';
COMMENT ON COLUMN punches.confirmed_at IS 'When.';
COMMENT ON TABLE time_requests IS 'Overtime and undertime requests.';
COMMENT ON COLUMN time_requests.id IS 'Primary key.';
COMMENT ON COLUMN time_requests.employee_id IS 'The employee this belongs to.';
COMMENT ON COLUMN time_requests.work_date IS 'The day.';
COMMENT ON COLUMN time_requests.request_type IS 'Kind.';
COMMENT ON COLUMN time_requests.minutes IS 'Minutes requested.';
COMMENT ON COLUMN time_requests.reason IS 'Why.';
COMMENT ON COLUMN time_requests.status IS 'Status.';
COMMENT ON COLUMN time_requests.filed_by_name IS 'Name of who filed it.';
COMMENT ON COLUMN time_requests.filed_at IS 'When filed.';
COMMENT ON COLUMN time_requests.decided_by IS 'Account that approved or declined it.';
COMMENT ON COLUMN time_requests.decided_by_name IS 'Name of who decided, kept if the account goes.';
COMMENT ON COLUMN time_requests.decided_at IS 'When it was decided.';
COMMENT ON COLUMN time_requests.decision_note IS 'Note from the approver to the employee.';
COMMENT ON TABLE punch_fix_requests IS 'Employee asks HR to add or correct a time-in/out the device missed.';
COMMENT ON COLUMN punch_fix_requests.id IS 'Primary key.';
COMMENT ON COLUMN punch_fix_requests.employee_id IS 'The employee this belongs to.';
COMMENT ON COLUMN punch_fix_requests.work_date IS 'The day.';
COMMENT ON COLUMN punch_fix_requests.direction IS 'Which punch.';
COMMENT ON COLUMN punch_fix_requests.requested_time IS 'Correct time.';
COMMENT ON COLUMN punch_fix_requests.next_day IS 'Time falls on the next calendar day.';
COMMENT ON COLUMN punch_fix_requests.cause IS 'What went wrong.';
COMMENT ON COLUMN punch_fix_requests.recorded_time IS 'Time on record when the request was sent.';
COMMENT ON COLUMN punch_fix_requests.reason IS 'Explanation.';
COMMENT ON COLUMN punch_fix_requests.status IS 'Status.';
COMMENT ON COLUMN punch_fix_requests.filed_by_name IS 'Name of who filed it.';
COMMENT ON COLUMN punch_fix_requests.filed_at IS 'When filed.';
COMMENT ON COLUMN punch_fix_requests.decided_by IS 'Account that approved or declined it.';
COMMENT ON COLUMN punch_fix_requests.decided_by_name IS 'Name of who decided, kept if the account goes.';
COMMENT ON COLUMN punch_fix_requests.decided_at IS 'When it was decided.';
COMMENT ON COLUMN punch_fix_requests.decision_note IS 'Note from the approver to the employee.';
COMMENT ON TABLE remote_work_days IS 'Work-from-home days HR declares for typhoons and emergencies.';
COMMENT ON COLUMN remote_work_days.id IS 'Primary key.';
COMMENT ON COLUMN remote_work_days.date_from IS 'First day.';
COMMENT ON COLUMN remote_work_days.date_to IS 'Last day.';
COMMENT ON COLUMN remote_work_days.reason IS 'e.g. Typhoon signal no. 3.';
COMMENT ON COLUMN remote_work_days.declared_by IS 'Who declared it.';
COMMENT ON COLUMN remote_work_days.declared_by_name IS 'Name of who declared it.';
COMMENT ON COLUMN remote_work_days.declared_at IS 'When.';
COMMENT ON TABLE remote_work_day_branches IS 'Branches a remote work day covers. No rows means every branch.';
COMMENT ON COLUMN remote_work_day_branches.remote_work_day_id IS 'The remote work day.';
COMMENT ON COLUMN remote_work_day_branches.branch_id IS 'Branch covered.';
COMMENT ON TABLE attendance_notices IS 'Memos HR sends about repeated lateness or AWOL. Never change pay.';
COMMENT ON COLUMN attendance_notices.id IS 'Primary key.';
COMMENT ON COLUMN attendance_notices.employee_id IS 'The employee this belongs to.';
COMMENT ON COLUMN attendance_notices.notice_kind IS 'Kind.';
COMMENT ON COLUMN attendance_notices.subject IS 'Subject line.';
COMMENT ON COLUMN attendance_notices.message IS 'Body.';
COMMENT ON COLUMN attendance_notices.dates IS 'The days it''s about.';
COMMENT ON COLUMN attendance_notices.sent_by IS 'Sender.';
COMMENT ON COLUMN attendance_notices.sent_by_name IS 'Name of the sender.';
COMMENT ON COLUMN attendance_notices.sent_at IS 'When sent.';
COMMENT ON COLUMN attendance_notices.acknowledged_at IS 'When the employee acknowledged it.';
COMMENT ON TABLE premium_rates IS 'Statutory premium multipliers by kind of day, versioned by effective date.';
COMMENT ON COLUMN premium_rates.day_type IS 'Kind of day.';
COMMENT ON COLUMN premium_rates.effective_from IS 'First day these rates apply.';
COMMENT ON COLUMN premium_rates.first_eight_hours IS 'Multiplier for the first 8 hours, e.g. 1.30.';
COMMENT ON COLUMN premium_rates.overtime IS 'Multiplier for overtime hours, e.g. 1.69.';
COMMENT ON COLUMN premium_rates.source IS 'Labor Code article or DOLE advisory.';
COMMENT ON COLUMN premium_rates.last_verified IS 'When someone last checked it against the source.';
COMMENT ON TABLE leave_types IS 'Company and statutory leave types (VL, SL, maternity, solo parent…).';
COMMENT ON COLUMN leave_types.id IS 'Short key, e.g. vl, ml; new types get lt-…';
COMMENT ON COLUMN leave_types.name IS 'e.g. Vacation leave.';
COMMENT ON COLUMN leave_types.code IS 'e.g. VL.';
COMMENT ON COLUMN leave_types.days_per_year IS 'Days a year, or per event for statutory leave; 0 = unlimited.';
COMMENT ON COLUMN leave_types.earning_kind IS 'How days are earned.';
COMMENT ON COLUMN leave_types.earning_per_month IS 'Days earned each month, for monthly accrual.';
COMMENT ON COLUMN leave_types.is_paid IS 'Unpaid leave is deducted in payroll.';
COMMENT ON COLUMN leave_types.carry_over_max IS 'Unused days that roll into next year.';
COMMENT ON COLUMN leave_types.count_by IS 'Skip rest days and holidays, or count every day.';
COMMENT ON COLUMN leave_types.eligibility IS 'Who can use it.';
COMMENT ON COLUMN leave_types.attachment_over_days IS 'Attachment required past this many days; null = never.';
COMMENT ON COLUMN leave_types.is_confidential IS 'Reason hidden from all but HR (VAWC).';
COMMENT ON COLUMN leave_types.legal_basis IS 'Law or policy it comes from.';
COMMENT ON COLUMN leave_types.is_active IS 'Active.';
COMMENT ON TABLE leave_requests IS 'Leave filed by or for an employee.';
COMMENT ON COLUMN leave_requests.id IS 'Primary key.';
COMMENT ON COLUMN leave_requests.employee_id IS 'The employee this belongs to.';
COMMENT ON COLUMN leave_requests.leave_type_id IS 'Type of leave.';
COMMENT ON COLUMN leave_requests.date_from IS 'First day.';
COMMENT ON COLUMN leave_requests.date_to IS 'Last day.';
COMMENT ON COLUMN leave_requests.half_day IS 'Half day, only when the dates are equal.';
COMMENT ON COLUMN leave_requests.days IS 'Days charged, after skipping rest days and holidays.';
COMMENT ON COLUMN leave_requests.reason IS 'Reason.';
COMMENT ON COLUMN leave_requests.attachment_file_id IS 'Medical certificate or other proof.';
COMMENT ON COLUMN leave_requests.attachment_name IS 'Name of the attached file.';
COMMENT ON COLUMN leave_requests.status IS 'Status.';
COMMENT ON COLUMN leave_requests.filed_by IS 'Account that filed it (the employee or HR).';
COMMENT ON COLUMN leave_requests.filed_by_name IS 'Name of who filed it.';
COMMENT ON COLUMN leave_requests.filed_at IS 'When filed.';
COMMENT ON COLUMN leave_requests.decided_by IS 'Account that approved or declined it.';
COMMENT ON COLUMN leave_requests.decided_by_name IS 'Name of who decided, kept if the account goes.';
COMMENT ON COLUMN leave_requests.decided_at IS 'When it was decided.';
COMMENT ON COLUMN leave_requests.decision_note IS 'Note from the approver to the employee.';
COMMENT ON TABLE leave_adjustments IS 'Manual changes HR makes to a balance or to the yearly leave credits.';
COMMENT ON COLUMN leave_adjustments.id IS 'Primary key.';
COMMENT ON COLUMN leave_adjustments.employee_id IS 'The employee this belongs to.';
COMMENT ON COLUMN leave_adjustments.leave_type_id IS 'Type of leave; null means the yearly credit pool (6 leaves a year).';
COMMENT ON COLUMN leave_adjustments.days IS 'Positive adds, negative removes (days, or whole leaves for the credit pool).';
COMMENT ON COLUMN leave_adjustments.reason IS 'Why.';
COMMENT ON COLUMN leave_adjustments.adjusted_by IS 'Who made it.';
COMMENT ON COLUMN leave_adjustments.adjusted_by_name IS 'Name of who made it.';
COMMENT ON COLUMN leave_adjustments.adjusted_at IS 'When.';
COMMENT ON TABLE leave_carry_overs IS 'Unused days brought into a year.';
COMMENT ON COLUMN leave_carry_overs.employee_id IS 'The employee.';
COMMENT ON COLUMN leave_carry_overs.leave_type_id IS 'Type of leave.';
COMMENT ON COLUMN leave_carry_overs.leave_year IS 'Year the days are carried into.';
COMMENT ON COLUMN leave_carry_overs.days IS 'Days carried over.';
COMMENT ON TABLE contribution_rate_versions IS 'SSS, PhilHealth, Pag-IBIG and BIR tables. A new circular is a new row, so past pay can still be recomputed.';
COMMENT ON COLUMN contribution_rate_versions.id IS 'Primary key.';
COMMENT ON COLUMN contribution_rate_versions.agency IS 'Agency.';
COMMENT ON COLUMN contribution_rate_versions.effective_from IS 'First pay date the rates apply to.';
COMMENT ON COLUMN contribution_rate_versions.source IS 'Circular or schedule it comes from.';
COMMENT ON COLUMN contribution_rate_versions.rates IS 'Rates in the agency''s shape (EE/ER rates, MSC range, tax brackets).';
COMMENT ON COLUMN contribution_rate_versions.saved_by IS 'Who saved this version.';
COMMENT ON COLUMN contribution_rate_versions.saved_by_name IS 'Name of who saved it (Built in for the starting tables).';
COMMENT ON COLUMN contribution_rate_versions.saved_at IS 'When.';
COMMENT ON TABLE payroll_runs IS 'One payroll per cutoff. Draft runs recompute from attendance; approved runs are locked.';
COMMENT ON COLUMN payroll_runs.id IS 'Primary key.';
COMMENT ON COLUMN payroll_runs.label IS 'e.g. Oct 1–15, 2026.';
COMMENT ON COLUMN payroll_runs.period_from IS 'Cutoff start.';
COMMENT ON COLUMN payroll_runs.period_to IS 'Cutoff end.';
COMMENT ON COLUMN payroll_runs.branch_id IS 'Branch, when run per office; null = all.';
COMMENT ON COLUMN payroll_runs.status IS 'Status.';
COMMENT ON COLUMN payroll_runs.created_by IS 'Who started it.';
COMMENT ON COLUMN payroll_runs.created_by_name IS 'Name of who started it.';
COMMENT ON COLUMN payroll_runs.created_at IS 'When.';
COMMENT ON COLUMN payroll_runs.computed_at IS 'Last recompute from attendance.';
COMMENT ON COLUMN payroll_runs.approved_by IS 'Who approved it (the CEO).';
COMMENT ON COLUMN payroll_runs.approved_by_name IS 'Name of who approved it.';
COMMENT ON COLUMN payroll_runs.approved_at IS 'When approved.';
COMMENT ON COLUMN payroll_runs.payslips_released_at IS 'When employees could see their payslips.';
COMMENT ON TABLE payroll_run_lines IS 'One employee''s pay in a run: the payslip.';
COMMENT ON COLUMN payroll_run_lines.payroll_run_id IS 'The run.';
COMMENT ON COLUMN payroll_run_lines.employee_id IS 'The employee.';
COMMENT ON COLUMN payroll_run_lines.basic_pay IS 'Half the monthly pay, or days employed if mid-cutoff.';
COMMENT ON COLUMN payroll_run_lines.absence_deductions IS 'Absences, AWOL, unpaid leave, undertime.';
COMMENT ON COLUMN payroll_run_lines.overtime_pay IS 'Approved overtime.';
COMMENT ON COLUMN payroll_run_lines.premium_pay IS 'Holiday, rest-day and night premiums.';
COMMENT ON COLUMN payroll_run_lines.gross_pay IS 'Gross.';
COMMENT ON COLUMN payroll_run_lines.sss_ee IS 'SSS employee share.';
COMMENT ON COLUMN payroll_run_lines.sss_er IS 'SSS employer share.';
COMMENT ON COLUMN payroll_run_lines.sss_ec IS 'Employees'' Compensation.';
COMMENT ON COLUMN payroll_run_lines.philhealth_ee IS 'PhilHealth employee share.';
COMMENT ON COLUMN payroll_run_lines.philhealth_er IS 'PhilHealth employer share.';
COMMENT ON COLUMN payroll_run_lines.pagibig_ee IS 'Pag-IBIG employee share.';
COMMENT ON COLUMN payroll_run_lines.pagibig_er IS 'Pag-IBIG employer share.';
COMMENT ON COLUMN payroll_run_lines.taxable_income IS 'Gross less contributions and non-taxable items.';
COMMENT ON COLUMN payroll_run_lines.withholding_tax IS 'BIR withholding tax.';
COMMENT ON COLUMN payroll_run_lines.net_pay IS 'Take-home pay.';
COMMENT ON COLUMN payroll_run_lines.computation IS 'Full line-by-line computation and the attendance it used.';
COMMENT ON TABLE payroll_adjustments IS 'Additions or deductions to one employee''s pay in a run.';
COMMENT ON COLUMN payroll_adjustments.id IS 'Primary key.';
COMMENT ON COLUMN payroll_adjustments.payroll_run_id IS 'The run.';
COMMENT ON COLUMN payroll_adjustments.employee_id IS 'The employee this belongs to.';
COMMENT ON COLUMN payroll_adjustments.label IS 'Shown on the payslip, e.g. Reimbursement.';
COMMENT ON COLUMN payroll_adjustments.amount IS 'Positive adds, negative deducts.';
COMMENT ON COLUMN payroll_adjustments.is_taxable IS 'Taxable items go into gross before tax.';
COMMENT ON COLUMN payroll_adjustments.reason IS 'Why.';
COMMENT ON COLUMN payroll_adjustments.reimbursement_claim_id IS 'Claim being paid, if any.';
COMMENT ON TABLE reimbursement_claims IS 'Expense claims with a receipt photo.';
COMMENT ON COLUMN reimbursement_claims.id IS 'Primary key.';
COMMENT ON COLUMN reimbursement_claims.employee_id IS 'The employee this belongs to.';
COMMENT ON COLUMN reimbursement_claims.category IS 'Expense category.';
COMMENT ON COLUMN reimbursement_claims.other_type IS 'What they typed when the category is Other.';
COMMENT ON COLUMN reimbursement_claims.merchant IS 'Store or provider on the receipt.';
COMMENT ON COLUMN reimbursement_claims.purchase_date IS 'Date on the receipt (within 60 days).';
COMMENT ON COLUMN reimbursement_claims.amount IS 'Amount claimed (max 50,000).';
COMMENT ON COLUMN reimbursement_claims.description IS 'What it was for.';
COMMENT ON COLUMN reimbursement_claims.receipt_file_id IS 'Receipt photo.';
COMMENT ON COLUMN reimbursement_claims.status IS 'Status.';
COMMENT ON COLUMN reimbursement_claims.filed_at IS 'When filed.';
COMMENT ON COLUMN reimbursement_claims.decided_by IS 'Account that approved or declined it.';
COMMENT ON COLUMN reimbursement_claims.decided_by_name IS 'Name of who decided, kept if the account goes.';
COMMENT ON COLUMN reimbursement_claims.decided_at IS 'When it was decided.';
COMMENT ON COLUMN reimbursement_claims.decision_note IS 'Note from the approver to the employee.';
COMMENT ON TABLE roles IS 'Roles that set a user''s workspace and module access.';
COMMENT ON COLUMN roles.id IS 'Role key, e.g. super-admin, hr.';
COMMENT ON COLUMN roles.name IS 'Display name.';
COMMENT ON COLUMN roles.description IS 'What the role is for.';
COMMENT ON COLUMN roles.workspace IS 'Workspace it signs into.';
COMMENT ON COLUMN roles.is_built_in IS 'Built-in roles can''t be deleted.';
COMMENT ON COLUMN roles.is_super_admin IS 'Manages roles, settings and other super admins.';
COMMENT ON TABLE role_module_access IS 'Access a role has to each HR-workspace module.';
COMMENT ON COLUMN role_module_access.role_id IS 'The role.';
COMMENT ON COLUMN role_module_access.module IS 'Module.';
COMMENT ON COLUMN role_module_access.access IS 'Level.';
COMMENT ON TABLE user_accounts IS 'Sign-in accounts. Linked to an employee when the user is one.';
COMMENT ON COLUMN user_accounts.id IS 'Primary key.';
COMMENT ON COLUMN user_accounts.username IS 'Sign-in name.';
COMMENT ON COLUMN user_accounts.builtin_key IS 'Marks the four built-in accounts.';
COMMENT ON COLUMN user_accounts.display_name IS 'Name shown in the app.';
COMMENT ON COLUMN user_accounts.password_hash IS 'Argon2id or bcrypt hash; never the password.';
COMMENT ON COLUMN user_accounts.employee_id IS 'Employee record, if any.';
COMMENT ON COLUMN user_accounts.role_id IS 'Role.';
COMMENT ON COLUMN user_accounts.status IS 'Status.';
COMMENT ON COLUMN user_accounts.must_change_password IS 'Force a change at next sign-in.';
COMMENT ON COLUMN user_accounts.last_sign_in_at IS 'Last successful sign-in.';
COMMENT ON COLUMN user_accounts.failed_attempts IS 'Failed sign-ins since the last success.';
COMMENT ON COLUMN user_accounts.locked_until IS 'Locked until this time.';
COMMENT ON COLUMN user_accounts.created_at IS 'When the row was created.';
COMMENT ON TABLE user_sessions IS 'Signed-in sessions. The browser holds the token in an HttpOnly cookie; only its hash is stored.';
COMMENT ON COLUMN user_sessions.token_hash IS 'SHA-256 of the session token.';
COMMENT ON COLUMN user_sessions.account_id IS 'Who is signed in.';
COMMENT ON COLUMN user_sessions.created_at IS 'Sign-in time.';
COMMENT ON COLUMN user_sessions.last_seen_at IS 'Last request; idle sessions expire.';
COMMENT ON COLUMN user_sessions.expires_at IS 'Hard expiry.';
COMMENT ON COLUMN user_sessions.user_agent IS 'Browser, for the sign-in log.';
COMMENT ON TABLE approval_workflows IS 'How each kind of request gets approved.';
COMMENT ON COLUMN approval_workflows.request_kind IS 'Kind of request.';
COMMENT ON COLUMN approval_workflows.remind_after_days IS 'Remind the approver after this many days (0 = never).';
COMMENT ON COLUMN approval_workflows.is_active IS 'Active.';
COMMENT ON TABLE approval_workflow_steps IS 'Ordered approval steps in a workflow.';
COMMENT ON COLUMN approval_workflow_steps.request_kind IS 'The workflow.';
COMMENT ON COLUMN approval_workflow_steps.step_no IS 'Order, starting at 1.';
COMMENT ON COLUMN approval_workflow_steps.approver_kind IS 'Who approves.';
COMMENT ON COLUMN approval_workflow_steps.role_id IS 'Role that approves, when approver_kind = role.';
COMMENT ON COLUMN approval_workflow_steps.over_days IS 'Only for leave longer than this many days.';
COMMENT ON TABLE audit_log IS 'Append-only trail: sign-ins, admin changes, 201 File views and edits, timekeeping changes, payroll approvals.';
COMMENT ON COLUMN audit_log.id IS 'Sequence.';
COMMENT ON COLUMN audit_log.occurred_at IS 'When.';
COMMENT ON COLUMN audit_log.actor_account_id IS 'Who did it.';
COMMENT ON COLUMN audit_log.actor_name IS 'Name at the time, kept if the account is deleted.';
COMMENT ON COLUMN audit_log.module IS 'Area.';
COMMENT ON COLUMN audit_log.action IS 'e.g. Viewed, Edited, Verified, Approved.';
COMMENT ON COLUMN audit_log.employee_id IS 'Whose record it touched, if any.';
COMMENT ON COLUMN audit_log.target IS 'What it touched, e.g. Valid Government ID.';
COMMENT ON COLUMN audit_log.detail IS 'Human-readable detail.';
COMMENT ON COLUMN audit_log.data IS 'Before/after values for edits.';
COMMENT ON TABLE announcements IS 'Company news shown on employee dashboards.';
COMMENT ON COLUMN announcements.id IS 'Primary key.';
COMMENT ON COLUMN announcements.title IS 'Headline.';
COMMENT ON COLUMN announcements.body IS 'Full text.';
COMMENT ON COLUMN announcements.branch_id IS 'Branch it''s for; null = everyone.';
COMMENT ON COLUMN announcements.posted_by IS 'Who posted it.';
COMMENT ON COLUMN announcements.posted_at IS 'When.';
COMMENT ON COLUMN announcements.expires_at IS 'Hide after this time.';
COMMENT ON TABLE compliance_filings IS 'Statutory remittances and returns: SSS, PhilHealth, Pag-IBIG, BIR.';
COMMENT ON COLUMN compliance_filings.id IS 'Primary key.';
COMMENT ON COLUMN compliance_filings.agency IS 'Agency.';
COMMENT ON COLUMN compliance_filings.filing IS 'e.g. Withholding tax remittance (1601-C).';
COMMENT ON COLUMN compliance_filings.period IS 'Period covered, e.g. 2026-09.';
COMMENT ON COLUMN compliance_filings.due_date IS 'Deadline.';
COMMENT ON COLUMN compliance_filings.filed_on IS 'When filed; status is computed from this and due_date.';
COMMENT ON COLUMN compliance_filings.reference_no IS 'Receipt or confirmation number.';
COMMENT ON COLUMN compliance_filings.filed_by IS 'Who filed it.';
COMMENT ON COLUMN compliance_filings.note IS 'Note.';
COMMENT ON TABLE job_requisitions IS 'Open positions being recruited for.';
COMMENT ON COLUMN job_requisitions.id IS 'Primary key.';
COMMENT ON COLUMN job_requisitions.position_id IS 'Position being filled.';
COMMENT ON COLUMN job_requisitions.openings IS 'How many to hire.';
COMMENT ON COLUMN job_requisitions.stage IS 'Stage.';
COMMENT ON COLUMN job_requisitions.opened_on IS 'When opened.';
COMMENT ON COLUMN job_requisitions.opened_by IS 'Who opened it.';

INSERT INTO schema_migrations (version) VALUES ('005_comments');

COMMIT;
