# One source for schema.sql, the data dictionary and the ERDs.
# Column: (name, type, flags, description[, allowed values])
# flags: PK, NN (not null), UQ, FK:table[.col], D:<default sql>

ID = ("id", "uuid", "PK D:gen_random_uuid()", "Primary key.")
CREATED = ("created_at", "timestamptz", "NN D:now()", "When the row was created.")

def emp(desc="The employee this belongs to.", nn=True):
    return ("employee_id", "uuid", ("NN " if nn else "") + "FK:employees", desc)

def acct(name, desc, nn=False):
    return (name, "uuid", ("NN " if nn else "") + "FK:user_accounts", desc)

def decision():
    return [
        acct("decided_by", "Account that approved or declined it."),
        ("decided_by_name", "text", "", "Name of who decided, kept if the account goes."),
        ("decided_at", "timestamptz", "", "When it was decided."),
        ("decision_note", "text", "", "Note from the approver to the employee."),
    ]

DOMAINS = [
 {
  "key": "org", "name": "Company & organization",
  "blurb": "The firm itself: settings, the branch / department / team tree, and the budgeted positions people are hired into.",
  "tables": [
   ("company_settings", "Single row of company-wide settings: identity, sign-in security, working time and tardiness flags.", [
     ("id", "smallint", "PK D:1", "Always 1; the table holds one row.", ["1"]),
     ("company_name", "text", "NN", "Legal or trade name shown on payslips and certificates."),
     ("tin", "text", "", "Company TIN, 000-000-000-00000."),
     ("address", "text", "", "Registered business address."),
     ("contact_email", "text", "", "HR contact address shown to employees."),
     ("min_password_length", "smallint", "NN D:8", "Minimum password length for user accounts."),
     ("lock_after_failed", "smallint", "NN D:5", "Failed sign-ins before an account locks."),
     ("lock_minutes", "smallint", "NN D:15", "How long a locked account stays locked."),
     ("idle_minutes", "smallint", "NN D:30", "Idle time before a session signs out."),
     ("tardy_consecutive_days", "smallint", "NN D:3", "Flag someone late this many work days in a row (0 = off)."),
     ("tardy_per_month", "smallint", "NN D:5", "Flag someone late this many times in a month (0 = off)."),
     ("updated_at", "timestamptz", "NN D:now()", "Last change."),
     acct("updated_by", "Account that made the last change."),
     ("logo_file_id", "uuid", "FK:files", "Company logo (Settings > Organization)."),
     ("default_timezone", "text", "NN D:'Asia/Manila'", "Timezone for anyone who hasn't picked their own."),
     ("currency", "text", "NN D:'PHP'", "Currency shown on amounts; payroll is computed in PHP."),
     ("work_week", "smallint[]", "NN D:'{1,2,3,4,5}'", "Working days, 0 = Sunday to 6 = Saturday. Leave counts only these days."),
     ("work_start", "time", "NN D:'08:30'", "Usual start of the working day."),
     ("work_end", "time", "NN D:'17:30'", "Usual end of the working day."),
     ("fiscal_year_start_month", "smallint", "NN D:1", "Month the fiscal year starts, 1 = January."),
     ("retention_months", "smallint", "NN D:0", "Keep records this many months after separation (0 = keep everything)."),
   ]),
   ("org_units", "The organization tree: one company, its branches, their departments and teams (clusters).", [
     ID,
     ("unit_type", "text", "NN", "Level in the tree.", ["company", "branch", "department", "team"]),
     ("name", "text", "NN", "Display name, e.g. Cebu HQ, Tax Advisory, RPM."),
     ("code", "text", "NN", "Short code used in tables and IDs, e.g. CEB, TAX."),
     ("parent_id", "uuid", "FK:org_units", "Parent unit; null only for the company."),
     ("head_employee_id", "uuid", "FK:employees", "Head of the unit (department head, partner)."),
     ("address", "text", "", "Street address; branches only."),
     ("is_active", "boolean", "NN D:true", "Inactive units stay for history but can't take new people."),
   ]),
   ("positions", "Budgeted job positions within a department.", [
     ID,
     ("title", "text", "NN", "Job title, e.g. Experienced Associate."),
     ("code", "text", "NN", "Short code, e.g. EA."),
     ("department_id", "uuid", "NN FK:org_units", "Department the position belongs to."),
     ("job_level", "text", "NN", "Seniority band.", ["Rank and file", "Supervisor", "Manager", "Executive"]),
     ("default_employment_type", "varchar(12)", "NN D:'PROBATIONARY'", "Type new hires into this position usually start on.", ["PROBATIONARY", "REGULAR", "FIXED_TERM"]),
     ("budgeted_slots", "smallint", "NN D:1", "Approved headcount for the position."),
     ("reports_to_position_id", "uuid", "FK:positions", "Position this one reports to."),
     ("description", "text", "", "Duties summary."),
     ("is_active", "boolean", "NN D:true", "Inactive positions can't take new hires."),
   ]),
   ("holidays", "Philippine regular and special non-working days, by proclamation.", [
     ("holiday_date", "date", "PK", "The day."),
     ("name", "text", "NN", "e.g. Araw ng Kagitingan."),
     ("holiday_type", "text", "NN", "Regular holidays pay 200%; special days 130%.", ["regular", "special"]),
     ("source", "text", "NN", "Proclamation number or reference."),
   ]),
  ],
 },
 {
  "key": "people", "name": "People & 201 File",
  "blurb": "The employee master record and everything kept in the 201 File: dependents, documents, job history, licenses, benefits and separation.",
  "tables": [
   ("employees", "The employee master record (201 File core). Fields marked BRD follow the New Employees Template (BRD v1.1, 11.2.1). Government numbers and BASIC_RATE are HR- and Payroll-only.", [
     ("employee_id", "varchar(20)", "PK D:'MSMA-' || lpad(nextval('employee_id_seq')::text, 5, '0')", "BRD. Unique employee identifier. Auto-generated if blank (MSMA-00001)."),
     ("last_name", "varchar(50)", "NN", "BRD. Surname. Letters only (spaces, hyphens, apostrophes, periods allowed)."),
     ("first_name", "varchar(50)", "NN", "BRD. Given name. Letters only."),
     ("middle_name", "varchar(50)", "", "BRD. Middle name. Letters only."),
     ("suffix", "varchar(10)", "", "Jr., Sr., III."),
     ("birth_date", "date", "NN", "BRD. Date of birth. Age must be 18 or older (checked by trigger)."),
     ("sex", "char(1)", "NN", "BRD. Gender. From the allowed values only.", ["M", "F"]),
     ("civil_status", "varchar(10)", "NN", "BRD. Marital status. From the allowed values only.", ["SINGLE", "MARRIED", "WIDOWED", "SEPARATED"]),
     ("mobile_no", "varchar(11)", "NN UQ", "BRD. Mobile number, 11 digits: 09XXXXXXXXX. Unique."),
     ("email", "varchar(100)", "NN UQ", "BRD. Email address (work). Valid email format. Unique."),
     ("date_hired", "date", "NN", "BRD. First day of employment. Not more than 30 days in the future (checked by trigger)."),
     ("employment_status", "varchar(12)", "NN D:'PROBATIONARY'", "BRD. Employment type.", ["PROBATIONARY", "REGULAR", "FIXED_TERM"]),
     ("tin", "text", "", "BRD. Tax Identification Number, encrypted by the app (AES-256-GCM). Required before first payroll."),
     ("sss_no", "text", "", "BRD. SSS number, encrypted by the app (AES-256-GCM). Required before first payroll."),
     ("philhealth_no", "text", "", "BRD. PhilHealth number, encrypted by the app (AES-256-GCM). Required before first payroll."),
     ("pagibig_no", "text", "", "BRD. Pag-IBIG MID number, encrypted by the app (AES-256-GCM). Required before first payroll."),
     ("tin_hash", "text", "UQ", "Fingerprint of the TIN (HMAC-SHA256), so no two employees share one."),
     ("sss_no_hash", "text", "UQ", "Fingerprint of the SSS number (HMAC-SHA256), so no two employees share one."),
     ("philhealth_no_hash", "text", "UQ", "Fingerprint of the PhilHealth number (HMAC-SHA256), so no two employees share one."),
     ("pagibig_no_hash", "text", "UQ", "Fingerprint of the Pag-IBIG MID (HMAC-SHA256), so no two employees share one."),
     ("basic_rate", "numeric(12,2)", "NN", "BRD. Basic monthly salary in PHP; must be > 0. Restricted to HR and Payroll."),
     ("nationality", "varchar(50)", "NN D:'Filipino'", "Nationality."),
     ("photo_file_id", "uuid", "FK:files", "ID photo."),
     ("personal_email", "varchar(100)", "", "Personal email."),
     ("address_line", "text", "", "House no., street, barangay."),
     ("city", "varchar(100)", "", "City or municipality."),
     ("province", "varchar(100)", "", "Province."),
     ("emergency_name", "varchar(100)", "", "Emergency contact person."),
     ("emergency_relationship", "varchar(50)", "", "Their relationship to the employee."),
     ("emergency_phone", "varchar(20)", "", "Their phone number."),
     ("position_id", "uuid", "FK:positions", "Current position."),
     ("org_unit_id", "uuid", "FK:org_units", "Team, or the department when not in a team."),
     ("supervisor_id", "varchar(20)", "FK:employees", "Immediate supervisor."),
     ("record_status", "varchar(10)", "NN D:'ACTIVE'", "Whether the person is currently working here.", ["ACTIVE", "ON_LEAVE", "SUSPENDED", "SEPARATED"]),
     ("regularization_date", "date", "", "When the employee became REGULAR."),
     ("separation_date", "date", "", "Last day, once separated."),
     ("work_schedule", "text", "", "Schedule as shown on the 201 File, e.g. Mon-Fri, 8:30 AM - 5:00 PM."),
     ("default_shift_id", "uuid", "FK:shift_templates", "Usual shift; overridden per day in schedule_overrides."),
     ("face_enrolled", "boolean", "NN D:false", "Face template enrolled for face-scan clock-in."),
     CREATED,
     ("updated_at", "timestamptz", "NN D:now()", "Last change."),
   ]),
   ("dependents", "Spouse and children, for HMO enrollment and leave eligibility.", [
     ID, emp(),
     ("full_name", "text", "NN", "Dependent's name."),
     ("relationship", "text", "NN", "Relationship.", ["Spouse", "Child"]),
     ("birth_date", "date", "", "Birth date (children)."),
     ("hmo_enrolled", "boolean", "NN D:false", "Enrolled as an HMO dependent."),
   ]),
   ("files", "Uploaded files: documents, receipts, photos. Kept in `content` for now; object storage later.", [
     ID,
     ("storage_key", "text", "NN UQ", "Object-storage key."),
     ("file_name", "text", "NN", "Original file name, encrypted by the app (AES-256-GCM)."),
     ("content_type", "text", "NN", "MIME type."),
     ("size_bytes", "bigint", "NN", "File size."),
     ("sha256", "text", "", "Checksum, to catch duplicates."),
     ("content", "bytea", "", "The file itself, encrypted by the app (AES-256-GCM), while files are kept in the database (null once moved to object storage)."),
     acct("uploaded_by", "Account that uploaded it."),
     ("uploaded_at", "timestamptz", "NN D:now()", "Upload time."),
   ]),
   ("employee_documents", "Pre-employment and identity documents in the 201 File checklist.", [
     ID, emp(),
     ("document_type", "text", "NN", "Checklist item.", ["Application Form / Resume", "Birth Certificate (PSA)", "Marriage Certificate (PSA)", "Child's Birth Certificate", "Valid Government ID", "Diploma / Transcript of Records", "Professional License", "Certificate of Employment (Previous)", "NBI Clearance", "Police/Barangay Clearance", "Pre-Employment Medical Result"]),
     ("status", "text", "NN D:'Missing'", "Where it stands.", ["Missing", "Submitted", "Verified", "Not applicable"]),
     ("file_id", "uuid", "FK:files", "The uploaded scan."),
     ("file_name", "text", "", "Name of the submitted file, encrypted by the app (AES-256-GCM)."),
     ("submitted_at", "timestamptz", "", "When it was uploaded."),
     acct("verified_by", "HR account that verified it."),
     ("verified_by_name", "text", "", "Name of who verified it, kept if the account goes."),
     ("verified_at", "timestamptz", "", "When it was verified."),
     ("id_type", "text", "", "For government IDs: UMID, Passport, Driver's License…"),
     ("reference_no", "text", "", "ID or license number, encrypted by the app (AES-256-GCM)."),
     ("expires_on", "date", "", "Expiry of the ID, license or clearance; drives renewal alerts."),
     ("note", "text", "", "HR note."),
   ]),
   ("job_events", "Employment history: hires, promotions, transfers, salary changes, separations.", [
     ID, emp(),
     ("event_kind", "text", "NN", "What happened.", ["Hired", "Promotion", "Transfer", "Salary adjustment", "Regularization", "Supervisor change", "Status change", "Separation"]),
     ("effective_date", "date", "NN", "When it takes effect."),
     ("changes", "jsonb", "NN D:'[]'", "List of {label, from, to} field changes."),
     ("remarks", "text", "", "Personnel action notice number or remarks."),
     acct("recorded_by", "Account that recorded it."),
     ("recorded_by_name", "text", "NN", "Name of who recorded it, kept if the account goes."),
     ("recorded_at", "timestamptz", "NN D:now()", "When it was recorded."),
   ]),
   ("professional_licenses", "PRC licenses (CPA, lawyer) and CPD unit progress.", [
     ID, emp(),
     ("license_type", "text", "NN", "e.g. CPA."),
     ("license_number", "text", "NN", "PRC license number, encrypted by the app (AES-256-GCM)."),
     ("expires_on", "date", "", "License validity."),
     ("cpd_units_earned", "numeric(5,1)", "NN D:0", "CPD units earned this cycle."),
     ("cpd_units_required", "numeric(5,1)", "NN D:60", "CPD units required for renewal."),
     ("cycle_end_date", "date", "", "End of the current CPD compliance cycle."),
   ]),
   ("employee_benefits", "HMO and government benefit memberships.", [
     ID, emp(),
     ("benefit_name", "text", "NN", "e.g. HMO, HMO — Dependent."),
     ("provider", "text", "NN", "e.g. Maxicare."),
     ("member_no", "text", "", "Membership or card number."),
     ("status", "text", "NN", "Enrollment status.", ["Active", "Pending", "Not enrolled"]),
   ]),
   ("performance_reviews", "Appraisals, annual and mid-year.", [
     ID, emp(),
     ("review_period", "text", "NN", "e.g. 2026 Mid-year review."),
     ("reviewer_id", "uuid", "FK:employees", "Who reviewed."),
     ("rating", "numeric(3,1)", "", "Score out of 5."),
     ("status", "text", "NN D:'Pending'", "Review status.", ["Pending", "Submitted", "Completed"]),
     ("completed_at", "timestamptz", "", "When it was completed."),
   ]),
   ("training_records", "Assigned trainings and their progress.", [
     ID, emp(),
     ("course", "text", "NN", "Course name."),
     ("due_date", "date", "", "Deadline."),
     ("status", "text", "NN D:'Not started'", "Progress.", ["Not started", "In progress", "Completed"]),
     ("completed_on", "date", "", "Completion date."),
   ]),
   ("employee_cases", "Employee relations cases a partner or HR files.", [
     ID, emp(),
     ("case_type", "text", "NN", "Kind of case.", ["Attendance", "Conduct", "Performance", "Grievance"]),
     ("status", "text", "NN D:'Open'", "Case status.", ["Open", "Under review", "Resolved"]),
     ("summary", "text", "NN", "What happened and what was done, encrypted by the app (AES-256-GCM)."),
     acct("filed_by", "Account that filed it.", nn=True),
     ("filed_on", "date", "NN D:current_date", "Filing date."),
   ]),
   ("company_assets", "Laptops, IDs, access cards and phones issued to employees.", [
     ID,
     ("asset_tag", "text", "NN UQ", "Inventory tag, e.g. LT-0231."),
     ("asset_type", "text", "NN", "e.g. Laptop, Company ID, Access Card."),
     ("assigned_employee_id", "uuid", "FK:employees", "Who has it now."),
     ("issued_on", "date", "", "Issue date."),
     ("returned_on", "date", "", "Return date."),
     ("status", "text", "NN D:'Issued'", "Condition.", ["Issued", "Returned", "Under repair"]),
   ]),
   ("offboarding_cases", "Resignations and separations with clearance progress.", [
     ID, emp(),
     ("separation_type", "text", "NN", "e.g. Voluntary resignation."),
     ("reason", "text", "", "Stated reason, encrypted by the app (AES-256-GCM)."),
     ("notice_filed_on", "date", "", "When notice was given (30-day rule)."),
     ("last_day", "date", "NN", "Last working day."),
     ("stage", "text", "NN D:'Resignation filed'", "Where it stands.", ["Resignation filed", "Clearance in progress", "Final pay released"]),
     ("clearance", "jsonb", "NN D:'[]'", "List of {department, status} clearance sign-offs."),
   ]),
   ("certificate_requests", "COE and other certificates employees request.", [
     ID, emp(),
     ("certificate_type", "text", "NN", "e.g. Certificate of Employment."),
     ("purpose", "text", "NN", "e.g. Bank loan application."),
     ("status", "text", "NN D:'Pending'", "Status.", ["Pending", "Ready for pickup", "Released"]),
     ("requested_at", "timestamptz", "NN D:now()", "Request time."),
     ("released_at", "timestamptz", "", "Release time."),
   ]),
  ],
 },
 {
  "key": "time", "name": "Timekeeping & attendance",
  "blurb": "Shifts, schedules, punches from biometric and face devices, and the requests that adjust them. Daily results (late, undertime, overtime) are computed from these, not stored.",
  "tables": [
   ("shift_templates", "Work shifts: Busy season, Peak season, Mid shift, Flexible time.", [
     ("id", "varchar(20)", "PK", "Short key, e.g. sh-day; new shifts get sh-…"),
     ("name", "text", "NN UQ", "Shift name."),
     ("start_time", "time", "NN", "Start, local time."),
     ("end_time", "time", "NN", "End; earlier than start means it ends next day."),
     ("break_minutes", "smallint", "NN D:60", "Unpaid break length."),
     ("break_start", "time", "NN", "When lunch starts; lunch out/in are recorded from it."),
     ("grace_minutes", "smallint", "NN D:5", "Minutes after start before someone is late."),
     ("rest_days", "smallint[]", "NN D:'{0,6}'", "Days off, 0 = Sunday."),
     ("is_flexible", "boolean", "NN D:false", "Clock in any time in the window; only hours worked count."),
     ("required_hours", "numeric(4,2)", "", "Hours a flexible day needs."),
     ("is_active", "boolean", "NN D:true", "Retired shifts stay for history."),
   ]),
   ("schedule_overrides", "A different shift, or a rest day, for one person on one date.", [
     ("employee_id", "uuid", "PK FK:employees", "The employee."),
     ("work_date", "date", "PK", "The date."),
     ("shift_id", "uuid", "FK:shift_templates", "Shift that day; null means a rest day."),
     acct("set_by", "Account that set it."),
   ]),
   ("attendance_devices", "Registered biometric scanners and face kiosks.", [
     ID,
     ("name", "text", "NN", "e.g. Cebu HQ lobby, 8F."),
     ("device_type", "text", "NN", "Kind of device.", ["biometric", "face"]),
     ("branch_id", "uuid", "NN FK:org_units", "Branch it's installed in."),
     ("serial_no", "text", "UQ", "Hardware serial."),
     ("is_registered", "boolean", "NN D:true", "Punches from unregistered devices get flagged."),
   ]),
   ("punches", "Every time-in and time-out. Never deleted; HR sets bad ones aside.", [
     ID, emp(),
     ("work_date", "date", "NN", "Schedule day it belongs to (an overnight shift's 6 AM out counts for the day before)."),
     ("punched_at", "timestamptz", "NN", "The moment of the punch."),
     ("direction", "text", "NN", "Time-in or time-out.", ["in", "out"]),
     ("source", "text", "NN", "Where it came from.", ["biometric", "face", "manual", "remote"]),
     ("device_id", "uuid", "FK:attendance_devices", "Device that recorded it."),
     ("device_label", "text", "", "Where it came from as shown on the record, e.g. Added by HR, Remote · face scan."),
     ("device_branch", "text", "", "Branch of the device (or of the person, for manual punches)."),
     ("face_match", "smallint", "", "Face recognition match, 0–100."),
     ("reason", "text", "", "Why HR added it (manual punches), or the remote work day's reason."),
     acct("recorded_by", "Account that added a manual or remote punch."),
     ("recorded_by_name", "text", "", "Name of who recorded it."),
     ("voided_reason", "text", "", "Why HR set it aside."),
     acct("voided_by", "Who set it aside."),
     ("voided_by_name", "text", "", "Name of who set it aside."),
     ("voided_at", "timestamptz", "", "When."),
     acct("confirmed_by", "HR looked at a flagged punch and kept it."),
     ("confirmed_by_name", "text", "", "Name of who kept it."),
     ("confirmed_at", "timestamptz", "", "When."),
   ]),
   ("time_requests", "Overtime and undertime requests.", [
     ID, emp(),
     ("work_date", "date", "NN", "The day."),
     ("request_type", "text", "NN", "Kind.", ["overtime", "undertime"]),
     ("minutes", "smallint", "NN", "Minutes requested."),
     ("reason", "text", "NN", "Why."),
     ("status", "text", "NN D:'pending'", "Status.", ["pending", "approved", "declined"]),
     ("filed_by_name", "text", "NN", "Name of who filed it."),
     ("filed_at", "timestamptz", "NN D:now()", "When filed."),
     *decision(),
   ]),
   ("punch_fix_requests", "Employee asks HR to add or correct a time-in/out the device missed.", [
     ID, emp(),
     ("work_date", "date", "NN", "The day."),
     ("direction", "text", "NN", "Which punch.", ["in", "out"]),
     ("requested_time", "time", "NN", "Correct time."),
     ("next_day", "boolean", "NN D:false", "Time falls on the next calendar day."),
     ("cause", "text", "NN D:'not-recorded'", "What went wrong.", ["not-recorded", "wrong-time", "system-error", "other"]),
     ("recorded_time", "time", "", "Time on record when the request was sent."),
     ("reason", "text", "NN", "Explanation."),
     ("status", "text", "NN D:'pending'", "Status.", ["pending", "approved", "declined"]),
     ("filed_by_name", "text", "NN", "Name of who filed it."),
     ("filed_at", "timestamptz", "NN D:now()", "When filed."),
     *decision(),
   ]),
   ("remote_work_days", "Work-from-home days HR declares for typhoons and emergencies.", [
     ID,
     ("date_from", "date", "NN", "First day."),
     ("date_to", "date", "NN", "Last day."),
     ("reason", "text", "NN", "e.g. Typhoon signal no. 3."),
     acct("declared_by", "Who declared it.", nn=True),
     ("declared_by_name", "text", "NN", "Name of who declared it."),
     ("declared_at", "timestamptz", "NN D:now()", "When."),
   ]),
   ("remote_work_day_branches", "Branches a remote work day covers. No rows means every branch.", [
     ("remote_work_day_id", "uuid", "PK FK:remote_work_days", "The remote work day."),
     ("branch_id", "uuid", "PK FK:org_units", "Branch covered."),
   ]),
   ("attendance_notices", "Memos HR sends about repeated lateness or AWOL. Never change pay.", [
     ID, emp(),
     ("notice_kind", "text", "NN", "Kind.", ["tardiness", "awol"]),
     ("subject", "text", "NN", "Subject line."),
     ("message", "text", "NN", "Body."),
     ("dates", "date[]", "NN", "The days it's about."),
     acct("sent_by", "Sender.", nn=True),
     ("sent_by_name", "text", "NN", "Name of the sender."),
     ("sent_at", "timestamptz", "NN D:now()", "When sent."),
     ("acknowledged_at", "timestamptz", "", "When the employee acknowledged it."),
   ]),
   ("premium_rates", "Statutory premium multipliers by kind of day, versioned by effective date.", [
     ("day_type", "text", "PK", "Kind of day.", ["ordinary", "rest", "special", "regular", "special-rest", "regular-rest"]),
     ("effective_from", "date", "PK", "First day these rates apply."),
     ("first_eight_hours", "numeric(4,2)", "NN", "Multiplier for the first 8 hours, e.g. 1.30."),
     ("overtime", "numeric(4,2)", "NN", "Multiplier for overtime hours, e.g. 1.69."),
     ("source", "text", "NN", "Labor Code article or DOLE advisory."),
     ("last_verified", "date", "NN", "When someone last checked it against the source."),
   ]),
  ],
 },
 {
  "key": "leave", "name": "Leave",
  "blurb": "Leave types and their rules, requests, manual adjustments and carry-over. Balances are always computed from these, never stored.",
  "tables": [
   ("leave_types", "Company and statutory leave types (VL, SL, maternity, solo parent…).", [
     ("id", "varchar(20)", "PK", "Short key, e.g. vl, ml; new types get lt-…"),
     ("name", "text", "NN UQ", "e.g. Vacation leave."),
     ("code", "text", "NN UQ", "e.g. VL."),
     ("days_per_year", "numeric(5,2)", "NN", "Days a year, or per event for statutory leave; 0 = unlimited."),
     ("earning_kind", "text", "NN", "How days are earned.", ["monthly", "yearly", "per-event", "unlimited"]),
     ("earning_per_month", "numeric(4,2)", "", "Days earned each month, for monthly accrual."),
     ("is_paid", "boolean", "NN D:true", "Unpaid leave is deducted in payroll."),
     ("carry_over_max", "numeric(5,2)", "NN D:0", "Unused days that roll into next year."),
     ("count_by", "text", "NN D:'workdays'", "Skip rest days and holidays, or count every day.", ["workdays", "calendar"]),
     ("eligibility", "text", "NN D:'everyone'", "Who can use it.", ["everyone", "female", "male-married", "solo-parent", "after-1-year", "after-6-months"]),
     ("attachment_over_days", "numeric(5,2)", "", "Attachment required past this many days; null = never."),
     ("is_confidential", "boolean", "NN D:false", "Reason hidden from all but HR (VAWC)."),
     ("legal_basis", "text", "NN", "Law or policy it comes from."),
     ("is_active", "boolean", "NN D:true", "Active."),
   ]),
   ("leave_requests", "Leave filed by or for an employee.", [
     ID, emp(),
     ("leave_type_id", "uuid", "NN FK:leave_types", "Type of leave."),
     ("date_from", "date", "NN", "First day."),
     ("date_to", "date", "NN", "Last day."),
     ("half_day", "text", "", "Half day, only when the dates are equal.", ["am", "pm"]),
     ("days", "numeric(5,2)", "NN", "Days charged, after skipping rest days and holidays."),
     ("reason", "text", "NN", "Reason, encrypted by the app (AES-256-GCM): it can describe an illness."),
     ("attachment_file_id", "uuid", "FK:files", "Medical certificate or other proof."),
     ("attachment_name", "text", "", "Name of the attached file, encrypted by the app (AES-256-GCM)."),
     ("status", "text", "NN D:'pending'", "Status.", ["pending", "approved", "rejected", "cancelled"]),
     acct("filed_by", "Account that filed it (the employee or HR).", nn=True),
     ("filed_by_name", "text", "NN", "Name of who filed it."),
     ("filed_at", "timestamptz", "NN D:now()", "When filed."),
     *decision(),
   ]),
   ("leave_adjustments", "Manual changes HR makes to a balance or to the yearly leave credits.", [
     ID, emp(),
     ("leave_type_id", "varchar(20)", "FK:leave_types", "Type of leave; null means the yearly credit pool (6 leaves a year)."),
     ("days", "numeric(5,2)", "NN", "Positive adds, negative removes (days, or whole leaves for the credit pool)."),
     ("reason", "text", "NN", "Why."),
     acct("adjusted_by", "Who made it.", nn=True),
     ("adjusted_by_name", "text", "NN", "Name of who made it."),
     ("adjusted_at", "timestamptz", "NN D:now()", "When."),
   ]),
   ("leave_carry_overs", "Unused days brought into a year.", [
     ("employee_id", "uuid", "PK FK:employees", "The employee."),
     ("leave_type_id", "uuid", "PK FK:leave_types", "Type of leave."),
     ("leave_year", "smallint", "PK", "Year the days are carried into."),
     ("days", "numeric(5,2)", "NN", "Days carried over."),
   ]),
  ],
 },
 {
  "key": "pay", "name": "Payroll & reimbursements",
  "blurb": "Contribution rate versions, payroll runs frozen from attendance once approved, adjustments, and expense claims. An employee's payslip is their line in an approved run.",
  "tables": [
   ("contribution_rate_versions", "SSS, PhilHealth, Pag-IBIG and BIR tables. A new circular is a new row, so past pay can still be recomputed.", [
     ID,
     ("agency", "text", "NN", "Agency.", ["sss", "philhealth", "pagibig", "bir"]),
     ("effective_from", "date", "NN", "First pay date the rates apply to."),
     ("source", "text", "NN", "Circular or schedule it comes from."),
     ("rates", "jsonb", "NN", "Rates in the agency's shape (EE/ER rates, MSC range, tax brackets)."),
     acct("saved_by", "Who saved this version."),
     ("saved_by_name", "text", "NN", "Name of who saved it (Built in for the starting tables)."),
     ("saved_at", "timestamptz", "NN D:now()", "When."),
   ]),
   ("payroll_runs", "One payroll per cutoff. Draft runs recompute from attendance; approved runs are locked.", [
     ID,
     ("label", "text", "NN", "e.g. Oct 1–15, 2026."),
     ("period_from", "date", "NN", "Cutoff start."),
     ("period_to", "date", "NN", "Cutoff end."),
     ("branch_id", "uuid", "FK:org_units", "Branch, when run per office; null = all."),
     ("status", "text", "NN D:'draft'", "Status.", ["draft", "approved"]),
     acct("created_by", "Who started it.", nn=True),
     ("created_by_name", "text", "NN", "Name of who started it."),
     ("created_at", "timestamptz", "NN D:now()", "When."),
     ("computed_at", "timestamptz", "NN D:now()", "Last recompute from attendance."),
     acct("approved_by", "Who approved it (the CEO)."),
     ("approved_by_name", "text", "", "Name of who approved it."),
     ("approved_at", "timestamptz", "", "When approved."),
     ("payslips_released_at", "timestamptz", "", "When employees could see their payslips."),
   ]),
   ("payroll_run_lines", "One employee's pay in a run: the payslip.", [
     ("payroll_run_id", "uuid", "PK FK:payroll_runs", "The run."),
     ("employee_id", "uuid", "PK FK:employees", "The employee."),
     ("basic_pay", "numeric(12,2)", "NN", "Half the monthly pay, or days employed if mid-cutoff."),
     ("absence_deductions", "numeric(12,2)", "NN D:0", "Absences, AWOL, unpaid leave, undertime."),
     ("overtime_pay", "numeric(12,2)", "NN D:0", "Approved overtime."),
     ("premium_pay", "numeric(12,2)", "NN D:0", "Holiday, rest-day and night premiums."),
     ("gross_pay", "numeric(12,2)", "NN", "Gross."),
     ("sss_ee", "numeric(10,2)", "NN D:0", "SSS employee share."),
     ("sss_er", "numeric(10,2)", "NN D:0", "SSS employer share."),
     ("sss_ec", "numeric(10,2)", "NN D:0", "Employees' Compensation."),
     ("philhealth_ee", "numeric(10,2)", "NN D:0", "PhilHealth employee share."),
     ("philhealth_er", "numeric(10,2)", "NN D:0", "PhilHealth employer share."),
     ("pagibig_ee", "numeric(10,2)", "NN D:0", "Pag-IBIG employee share."),
     ("pagibig_er", "numeric(10,2)", "NN D:0", "Pag-IBIG employer share."),
     ("taxable_income", "numeric(12,2)", "NN", "Gross less contributions and non-taxable items."),
     ("withholding_tax", "numeric(12,2)", "NN D:0", "BIR withholding tax."),
     ("net_pay", "numeric(12,2)", "NN", "Take-home pay."),
     ("computation", "jsonb", "NN", "Full line-by-line computation and the attendance it used."),
   ]),
   ("payroll_adjustments", "Additions or deductions to one employee's pay in a run.", [
     ID,
     ("payroll_run_id", "uuid", "NN FK:payroll_runs", "The run."),
     emp(),
     ("label", "text", "NN", "Shown on the payslip, e.g. Reimbursement."),
     ("amount", "numeric(12,2)", "NN", "Positive adds, negative deducts."),
     ("is_taxable", "boolean", "NN D:false", "Taxable items go into gross before tax."),
     ("reason", "text", "NN", "Why."),
     ("reimbursement_claim_id", "uuid", "FK:reimbursement_claims", "Claim being paid, if any."),
   ]),
   ("reimbursement_claims", "Expense claims with a receipt photo. The employee's approver endorses them, then Accounting gives the final approval.", [
     ID, emp(),
     ("category", "text", "NN", "Expense category.", ["Transportation", "Meals & client meetings", "Office supplies", "Communication", "Training & seminars", "Medical", "Other"]),
     ("other_type", "text", "", "What they typed when the category is Other."),
     ("merchant", "text", "NN", "Store or provider on the receipt."),
     ("purchase_date", "date", "NN", "Date on the receipt (within 60 days)."),
     ("amount", "numeric(10,2)", "NN", "Amount claimed (max 50,000)."),
     ("description", "text", "NN", "What it was for."),
     ("receipt_file_id", "uuid", "NN FK:files", "Receipt photo."),
     ("status", "text", "NN D:'pending'", "Waiting for the approver, endorsed (waiting for Accounting), approved or rejected.", ["pending", "endorsed", "approved", "rejected"]),
     ("filed_at", "timestamptz", "NN D:now()", "When filed."),
     *decision(),
     acct("approver_decided_by", "Approver (the employee's supervisor) who endorsed or rejected it."),
     ("approver_decided_by_name", "text", "", "Name of that approver, kept if the account goes."),
     ("approver_decided_at", "timestamptz", "", "When the approver decided."),
     ("approver_note", "text", "", "The approver's note."),
   ]),
  ],
 },
 {
  "key": "access", "name": "Access, workflows & audit",
  "blurb": "Who can sign in and what they can do, how requests get approved, and the audit trail for every sensitive action.",
  "tables": [
   ("subscriptions", "The company's HRIS plan (SaaS): plan, seat limit and billing period. One row per period; the newest one not cancelled or expired is current.", [
     ID,
     ("plan_name", "text", "NN", "Plan the company is on, e.g. Starter, Business."),
     ("status", "text", "NN D:'active'", "Trial, active, past due (payment late), cancelled or expired.", ["trial", "active", "past_due", "cancelled", "expired"]),
     ("seat_limit", "integer", "", "Most sign-in accounts the plan covers (System Admin accounts don't count); empty = no limit."),
     ("billing_cycle", "text", "NN D:'monthly'", "How often it's billed.", ["monthly", "yearly"]),
     ("price_per_seat", "numeric(10,2)", "", "Price per seat per billing cycle."),
     ("currency", "text", "NN D:'PHP'", "Currency of the price."),
     ("starts_on", "date", "NN D:current_date", "First day of this subscription."),
     ("current_period_end", "date", "", "When the current billing period ends (renewal date)."),
     ("trial_ends_on", "date", "", "Last day of the trial, while on trial."),
     ("cancelled_at", "timestamptz", "", "When it was cancelled."),
     ("notes", "text", "", "Notes from our team, e.g. the contract or invoice reference."),
     CREATED,
     acct("created_by", "Account that set it up."),
     ("updated_at", "timestamptz", "NN D:now()", "Last change."),
     acct("updated_by", "Account that made the last change."),
   ]),
   ("roles", "The six fixed roles. What each may do is the access matrix in the app (src/lib/permissions.ts).", [
     ("id", "text", "PK", "Role id, e.g. super-admin, hr."),
     ("role_key", "text", "NN UQ", "Which of the six roles, as the access matrix names it.", ["system_admin", "super_admin", "hr", "approver", "accounting", "employee"]),
     ("name", "text", "NN UQ", "Display name."),
     ("description", "text", "NN", "What the role is for."),
     ("workspace", "text", "NN", "Workspace it signs into.", ["employee", "manager", "admin"]),
     ("is_built_in", "boolean", "NN D:false", "Built-in roles can't be deleted."),
     ("is_super_admin", "boolean", "NN D:false", "Manages roles, settings and other super admins."),
   ]),
   ("user_accounts", "Sign-in accounts. Linked to an employee when the user is one.", [
     ID,
     ("username", "text", "NN UQ", "Sign-in name."),
     ("builtin_key", "text", "UQ", "Marks the accounts created at setup.", ["superadmin", "admin", "hr", "employee"]),
     ("display_name", "text", "NN", "Name shown in the app."),
     ("password_hash", "text", "NN", "Argon2id or bcrypt hash; never the password."),
     ("employee_id", "uuid", "UQ FK:employees", "Employee record, if any."),
     ("role_id", "text", "NN FK:roles", "Role."),
     ("status", "text", "NN D:'active'", "Status.", ["active", "disabled"]),
     ("must_change_password", "boolean", "NN D:false", "Force a change at next sign-in."),
     ("last_sign_in_at", "timestamptz", "", "Last successful sign-in."),
     ("failed_attempts", "smallint", "NN D:0", "Failed sign-ins since the last success."),
     ("locked_until", "timestamptz", "", "Locked until this time."),
     CREATED,
     ("mfa_secret", "text", "", "Authenticator-app (TOTP) secret once two-factor sign-in is on, encrypted by the app (AES-256-GCM)."),
     ("mfa_pending_secret", "text", "", "Secret being set up, until the first code confirms it; encrypted by the app."),
     ("mfa_enabled_at", "timestamptz", "", "When two-factor sign-in was turned on; empty = off."),
     ("mfa_last_step", "bigint", "", "Last 30-second code step used, so a code can't be used twice."),
   ]),
   ("user_sessions", "Signed-in sessions. The browser holds the token in an HttpOnly cookie; only its hash is stored.", [
     ("token_hash", "text", "PK", "SHA-256 of the session token."),
     ("account_id", "uuid", "NN FK:user_accounts", "Who is signed in."),
     ("created_at", "timestamptz", "NN D:now()", "Sign-in time."),
     ("last_seen_at", "timestamptz", "NN D:now()", "Last request; idle sessions expire."),
     ("expires_at", "timestamptz", "NN", "Hard expiry."),
     ("user_agent", "text", "", "Browser, for the sign-in log."),
     ("mfa_pending", "boolean", "NN D:false", "Password was right but the two-factor code isn't entered yet: this session can only enter the code."),
   ]),
   ("mfa_backup_codes", "One-time backup codes for two-factor sign-in, for when the phone is lost. Only hashes are stored.", [
     ID,
     ("account_id", "uuid", "NN FK:user_accounts", "Whose code."),
     ("code_hash", "text", "NN", "Argon2 hash of the code; never the code."),
     ("used_at", "timestamptz", "", "When it was used; each code works once."),
     CREATED,
   ]),
   ("approval_workflows", "How each kind of request gets approved.", [
     ("request_kind", "text", "PK", "Kind of request.", ["leave", "overtime", "undertime", "correction", "profile"]),
     ("remind_after_days", "smallint", "NN D:2", "Remind the approver after this many days (0 = never)."),
     ("is_active", "boolean", "NN D:true", "Active."),
   ]),
   ("approval_workflow_steps", "Ordered approval steps in a workflow.", [
     ("request_kind", "text", "PK FK:approval_workflows.request_kind", "The workflow."),
     ("step_no", "smallint", "PK", "Order, starting at 1."),
     ("approver_kind", "text", "NN", "Who approves.", ["supervisor", "department-head", "role"]),
     ("role_id", "text", "FK:roles", "Role that approves, when approver_kind = role."),
     ("over_days", "numeric(5,2)", "", "Only for leave longer than this many days."),
   ]),
   ("audit_log", "Append-only trail: sign-ins, admin changes, 201 File views and edits, timekeeping changes, payroll approvals.", [
     ("id", "bigint", "PK D:generated always as identity", "Sequence."),
     ("occurred_at", "timestamptz", "NN D:now()", "When."),
     acct("actor_account_id", "Who did it."),
     ("actor_name", "text", "NN", "Name at the time, kept if the account is deleted."),
     ("module", "text", "NN", "Area.", ["Sign-in", "Administration", "People", "Documents", "Timekeeping", "Leave", "Reimbursements", "Payroll"]),
     ("action", "text", "NN", "e.g. Viewed, Edited, Verified, Approved."),
     ("employee_id", "uuid", "FK:employees", "Whose record it touched, if any."),
     ("target", "text", "NN", "What it touched, e.g. Valid Government ID."),
     ("detail", "text", "", "Human-readable detail."),
     ("data", "jsonb", "", "Before/after values for edits."),
   ]),
  ],
 },
 {
  "key": "comms", "name": "Announcements & compliance",
  "blurb": "Company announcements, the statutory filing calendar and job openings.",
  "tables": [
   ("announcements", "Company news shown on employee dashboards.", [
     ID,
     ("title", "text", "NN", "Headline."),
     ("body", "text", "", "Full text."),
     ("branch_id", "uuid", "FK:org_units", "Branch it's for; null = everyone."),
     acct("posted_by", "Who posted it.", nn=True),
     ("posted_at", "timestamptz", "NN D:now()", "When."),
     ("expires_at", "timestamptz", "", "Hide after this time."),
   ]),
   ("compliance_filings", "Statutory remittances and returns: SSS, PhilHealth, Pag-IBIG, BIR.", [
     ID,
     ("agency", "text", "NN", "Agency.", ["SSS", "PhilHealth", "Pag-IBIG", "BIR"]),
     ("filing", "text", "NN", "e.g. Withholding tax remittance (1601-C)."),
     ("period", "text", "NN", "Period covered, e.g. 2026-09."),
     ("due_date", "date", "NN", "Deadline."),
     ("filed_on", "date", "", "When filed; status is computed from this and due_date."),
     ("reference_no", "text", "", "Receipt or confirmation number."),
     acct("filed_by", "Who filed it."),
     ("note", "text", "", "Note."),
   ]),
   ("job_requisitions", "Open positions being recruited for.", [
     ID,
     ("position_id", "uuid", "NN FK:positions", "Position being filled."),
     ("openings", "smallint", "NN D:1", "How many to hire."),
     ("stage", "text", "NN D:'Sourcing'", "Stage.", ["Sourcing", "Interviewing", "Offer extended", "Filled", "Cancelled"]),
     ("opened_on", "date", "NN D:current_date", "When opened."),
     acct("opened_by", "Who opened it."),
   ]),
  ],
 },
]
